[package]
name = "dsp_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
circular-buffer = "0.1.3"
fundsp = "0.15.0"
numeric-array = "0.5.2"
rand = "0.8.5"
